### ISSUE TITLE
Share `read-only` web3.storage capabilities

### ISSUE THREAD

**Issue by DougAnderson444** [fireproof-storage/fireproof#105]
I'm looking to share `read-only` pointers to a database. After seeing [this comment](https://discord.com/channels/1142273421674303619/1142286889588629604/1204515931938889738) I'm under the impression this isn't a feature yet.

Am I right in deducing that if we add a function similar to `shareWith(did)` with _only_ [`can: 'clock/head'`](https://github.com/web3-storage/specs/blob/main/w3-clock.md#fetching-the-clock-head) we would create a read-only version of `shareWith`? 

https://github.com/fireproof-storage/fireproof/blob/a7391cc03b01b631efc74421d74d585dcb048fa4/packages/connect-ipfs/src/connect-ipfs-sharing.xts#L21

**Comment by DougAnderson444** [comment]
Also, what is the `.xts` extension that is being used here?

**Comment by jchris** [comment]
Thanks @DougAnderson444 -- this is a `.ts` file I just changed it because it is breaking the build. The IPFS connector is a long story, but the short version is the architecture is right, but it's currently way more complex than it needs to be, because the web3.storage team added delegation features we can use to no longer need most of that code. I'm not sure where to find it in their docs, but basically their email validation agent sets up the ablity to delegate so that Fireproof code doesn't have to manage devices anymore.

IPFS has gotten to be higher priority in the last couple of weeks, so if you are up for it, I'd love to have a [call and learn more about your use case](https://savvycal.com/jchris/fireproof). Or you can email me async at jchris@fireproof.storage

**Comment by jchris** [comment]
Thanks for the call. Check out the demo video linked here https://github.com/w3s-project/project-tracking/issues/1#issuecomment-2042758387

**Comment by jchris** [comment]
@DougAnderson444 I updated the IPFS connector code so the build is clean. I haven't had a chance to test drive it yet, but at least now the busywork is cleaned up https://github.com/fireproof-storage/fireproof/pull/108

**Comment by jchris** [comment]
Tracking current client update progress here https://github.com/fireproof-storage/fireproof/issues/111

**Comment by jchris** [comment]
closing as read-only is on our access control plans
